plugins:
#  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
permalink: /:year/:month/:title.html
exclude:
  - Gemfile
  - Gemfile.lock

paginate: 10
paginate_path: "/blog/:num/"