plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
permalink: /:year/:month/:title.html
exclude:
  - Gemfile
  - Gemfile.lock

pagination:
  enabled: true
  per_page: 10
  permalink: '/blog/:num/' # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  trail: 
    before: 2
    after: 2
  indexpage: 'blog.html'
  sort_reverse: true