title: deybismelendez.github.io

plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-seo-tag

permalink: /:year/:month/:title.html

# default excludes
exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - run.sh
    - LICENSE
    - README.md

# overrides your excluded items configuration and the default include array ([".htaccess"])
include:
    - .htaccess
    - node_modules/uglifier/index.js

paginate: 10
paginate_path: "/blog/:num/"

highlighter: rouge
markdown: kramdown
